# Generated by Django 2.0 on 2019-01-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0003_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_vote',
            name='downvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer_vote',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question_vote',
            name='downvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question_vote',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
    ]
