# Generated by Django 2.0 on 2019-01-08 08:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quora', '0003_auto_20190107_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer_Vote',
            new_name='AnswerVote',
        ),
        migrations.RenameModel(
            old_name='Question_Vote',
            new_name='QuestionVote',
        ),
    ]
