# Generated by Django 2.0 on 2019-01-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0004_auto_20190102_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_vote',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='answer_vote',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='question_vote',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='question_vote',
            name='upvote',
        ),
    ]
