# Generated by Django 2.0 on 2019-01-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0005_auto_20190102_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_vote',
            name='votes',
            field=models.IntegerField(default=False),
        ),
    ]
